# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kate Storey-Fisher
email: kstoreyf@stanford.edu 
description: "Astrophysicist &#160; | &#160; Kavli Fellow @ KIPAC, Stanford"
baseurl: "/ksf" # the subpath of your site, e.g. /blog
url: "https://cosmo.nyu.edu" # the base hostname & protocol for your site

# Logo settings
logo-image-url:
font-awesome-icon-logo:

# Social settings
github_username: kstoreyf
twitter_username:
facebook_URL:
instagram_username:

# Build settings
markdown: kramdown
#kramdown: 
#  parse_block_html: true

include:
  - sections
  - _pages

collections:
  - research
  - writing
  - outreach

compress_html:
  clippings: []
  blanklines: false
  comments: all
